#!/bin/bash
ADD=$2
JAR=/etc/aio	#Pasta das definições
RECEITA_PASTA=/home/apps/receitas	#Pasta das receitas
BASIS=$RECEITA_PASTA/basis	#Pasta das bases para receitas
RAIZ="https://raw.githubusercontent.com"
APPS=/home/apps	#Pasta dos apps
COMBURENT="pkg2appimage"
BINS=/usr/bin
LOCAL=/home/`whoami`/.local
LOCALBINS=$LOCAL/bin
LOCALICONS=$LOCAL/share/icons/hicolor/256x256/apps
ELINKS=$LOCAL/share/applications
OVEN=""
JARRA=""
PRODUTO=""
CAMINHO=`pwd`
AUTOINTEGRAR=0
VERSIONR=202101151120
ISLOCAL=0
troca=""
echo $CAMINHO
echo $1 $2 $3 $4 $5
### Funções
CALLLOCAL(){
if [[ "$2" == "local" || "$3" == "local" || "$4" == "local" || "$5" == "local" || "$2" == "--local" || "$3" == "--local" || "$4" == "--local" || "$5" == "--local" ]]; then
  echo "local"
  ISLOCAL=1
fi
}

CHECKINTEGRATE(){
if [[ "$1" == "--nointegrate" || "$2" == "--nointegrate" || "$3" == "--nointegrate" || "$4" == "--nointegrate" || "$5" == "--nointegrate" ]]; then
  AUTOINTEGRAR=1
fi
}

CKLOCALNAMES(){
if [ "$2"=="local" || "$2"=="nointegrate" || "$2"=="--local" || "$2"=="--nointegrate"]; then
	$2=""
fi
if [ "$3"=="local" || "$3"=="nointegrate" || "$3"=="--local" || "$3"=="--nointegrate"]; then
	$3=""
fi
if [ "$4"=="local" || "$4"=="nointegrate" || "$4"=="--local" || "$4"=="--nointegrate"]; then
	$4=""
fi
if [ "$5"=="local" || "$5"=="nointegrate" || "$5"=="--local" || "$5"=="--nointegrate"]; then
	$5=""
fi
ADD=`cat $JAR/system.aio | grep -w "$2$3$4$5:" | awk '{print $2}'`
}

CHECKAIOVERSION(){
AIOR=`cat /tmp/book | grep -w "aio:" | awk '{print $3}'`
echo "AIO: $AIOR"
if [ "$VERSIONR" -lt "$AIOR" ]; then
    troca=troca
    echo "Existe uma nova atualização do AIO."
    MSGU003
    GETAIO
fi
}

DOCOOK(){
PRATO=$RECEITA_PASTA/out/
MISTURA=$RECEITA_PASTA/$OVEN
FORNO=$MISTURA/$ADD.AppDir
if [ -e "$RECEITA_PASTA/$ADD.yml" ]; then
 cd $RECEITA_PASTA
 echo "##*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*##"
 pkg2appimage "$RECEITA_PASTA/$ADD.yml"	#COZINHA
 echo "##*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*##"
 echo "$MISTURA
 " 
 if [ -e "$MISTURA" ]; then 
    troca=troca
 #   if [ "$whoami"=="root" ]; then chmod 777 $MISTURA; chmod 777 $FORNO; chmod 777 $PRATO; fi ##Contenção para caso seja gerado com sudo    
 else echo "Não foi adicionada a tijela ao forno"; fi
 cd $CAMINHO
 if [ -e "$PRATO" ]; then	#Testa pra ver se foi cozinhado
  PRODUTO=`ls $RECEITA_PASTA/out/`	#Pega o nome do app criado
  APPNMLIST=`cat $JAR/aio.list | grep -w '$ADD: $PRODUTO'`; echo $APPNMLIST
  if [ "$APPNMLIST" == "$ADD: $PRODUTO" ]; then
   sed -i '/'$ADD'/d' $JAR/aio.list; echo "$ADD: $PRODUTO" >> $JAR/aio.list;
  else echo "$ADD: $PRODUTO" >> $JAR/aio.list;	#Coloca o nome do app novo na lista 
  fi
 else
  echo "A tigela não saiu do forno"
 fi
fi
}

DELBINS(){
	rm -RF $BINS/$ADD	#Remove o binário principal
	while IFS= read -r line
	do
	  ITEM=`cat $line | awk '{print $1}'`
	  echo $ITEM
	  if [[ "$ITEM" == "$ADD" ]]; then	#Cria uma lista dos parametros anteriormente adicionados
		echo `cat $line | awk '{print $2}'` >> /tmp/idata.aio 	
	  fi
	done < "$JAR/idata.aio"
	
	while IFS= read -r line
	do
	  IDATARM=`cat $line | awk {print $0}`
	  rm -Rf $ELINKS/$IDATARM	  #Remove os atalhos de integração
	done < "/tmp/idata.aio"
	
}

DEL(){
	EXISTAPP=`cat $JAR/aio.list | grep -w "$ADD:" | awk '{print $2}'`	#Detecta o nome do app antigo
	sed -i '/'$ADD'/d' $JAR/aio.list	#Remove da lista o nome do app existente
	rm -Rf $APPS/$EXISTAPP	#Remove a ligação
	if [[ -L "$BINS/$ADD" ]]; then
	  sudo bash -c "$DELBINS"
	fi
	rm -Rf $APPS/$EXISTAPP	#Remove o app existente
}

DELOVEN(){
 echo "FORNO: $OVEN"
 echo "$MISTURA"
 if [ -e "$FORNO" ]; then rm -Rf $MISTURA; echo "removendo Ingredintes"; else  echo "Pasta com Ingredientes não existe"; fi
 if [ -e "$PRATO" ]; then rm -Rf $PRATO; echo "removendo a prateleira"; else  echo "a preteleira não existe"; fi
}

#EXEINTEGRAR(){
#ATALHOS=`ls $FORNO/usr/share/applications/`
#while IFS= read -r line
#do
#  IDATARM=`cat $line | awk {print $0}`
#  cp -f $FORNO/usr/share/applications/$line $ELINKS/$line	  #Move os atalhos
#  sed 's|Exec=|Exec=$LOCALBINS/|g' $ELINKS/$line
#done < $ATALHOS
#echo "Atalhos integrados"
#UPDATEICONS
#}

#UPDATEICONS(){
# if [[ -e "$FORNO/*.svg" || -e "$FORNO/*.png" ]]; then
#  if [ -e "$FORNO/*.svg" ]; then 
#   ICONCAT=`ls $FORNO/*.svg`; cp -Rf $FORNO/$ICONCAT $RECEITA_PASTA/Icons; ln -s $RECEITA_PASTA/Icons/$ICONCAT $LOCALICONS/$ICONCAT
#   else ICONCAT=`ls $FORNO/*.png`;  cp -Rf $FORNO/$ICONCAT $RECEITA_PASTA/Icons; ln -s $RECEITA_PASTA/Icons/$ICONCAT $LOCALICONS/$ICONCAT; fi
# else
#  echo "Não existem ícones no forno"
# fi
#}

GETAIO(){
	rm -Rf $JAR/aio
	wget -q --show-progress $RAIZ/andryeltj/aio/master/aio -P $JAR
	chmod +x $JAR/aio
	AIOR=`cat $JAR/aio | grep -w "VERSIONR=" | awk '{print $2}'`
	echo "🗘 AIO: "$AIOR" < Atualizado para esta versão"
}

GETRECEITA(){
 ADD=`cat /tmp/book | grep -w "$ADD:" | awk '{print $2}'`
 JARRA=`cat /tmp/book | grep -w "$ADD" | awk '{print $4}'`
 if [ -e "$RECEITA_PASTA/$ADD.yml" ]; then rm -Rf $RECEITA_PASTA/$ADD.yml; fi
 echo "$RAIZ/$JARRA/$ADD.yml"
 wget -q --show-progress $RAIZ/$JARRA/$ADD.yml -P $RECEITA_PASTA/
# if [ "`whoami`"=="root" ]; then chmod 777 $RECEITA_PASTA/$ADD.yml; fi
 if [ -e "$RECEITA_PASTA/$ADD.yml" ]; then OVEN=`cat $RECEITA_PASTA/$ADD.yml | grep "app:" | awk '{print $2}'`; echo "OVEN:$OVEN" else echo "Receita não baixada"; fi
}

GETCOMBURENT(){
  GETNETBOOK
  JARRA=`cat /tmp/book | grep -w "$COMBURENT" | awk '{print $4}'`
  wget -q --show-progress $RAIZ/$JARRA/$COMBURENT -P /etc/aio/; chmod +x $JAR/$COMBURENT;
  if [ -e "$BINS/$COMBURENT" ]; then troca=troca; else sudo ln -s $JAR/$COMBURENT $BINS/$COMBURENT; fi
  if [ -e "$JAR/$COMBURENT" ]; then troca=troca; echo "Comburente adiquirido"; else echo "Falha ao adiquirir comburente"; fi 
  if [ -e "$BINS/$COMBURENT" ]; then troca=troca; echo "Comburente integrado ao sistema"; else echo "Falha ao integrar comburente"; fi 
}

GETNETBOOK(){
	if [[ -e "$JAR/jar.aio" ]]; then
	  troca=troca
	else
	  JARCONTENT
	fi
	if [[ -e "/tmp/book" ]]; then
	  rm -Rf /tmp/book	#REMOVE O LIVRO ANTIGO
	fi
	while IFS= read -r line
	do
		rm -Rf /tmp/book
		wget -q --show-progress -c $line/book -P /tmp/	#BAIXA O NOVO LIVRO
#		if [ "`whoami`" == "root" ]; then chmod 777 /tmp/book; fi
	done < $JAR/jar.aio
}

GETSUGESTS(){ 
if [ -e "$RECEITA_PASTA/$ADD.yml" ]; then
 SUGESTS=`cat $RECEITA_PASTA/$ADD.yml | grep -w "sugestname:"`	#Cria a lista de provaveis nomes para o app atravez da receita
 sed -i '/'$ADD'/d' $JAR/system.aio
 for n in $SUGESTS; do
  echo $n: $ADD >> $JAR/system.aio
  sed -i '/sugests/d' $JAR/system.aio
  shift
 done
else
 echo "A receita não existe para ver se existem sugestões de palavras"
fi
}

JARCONTENT(){
  echo "https://raw.githubusercontent.com/andryeltj/receitas/master" > $JAR/jar.aio
}

LISTJAR(){
 echo "
 #######################################################
 #######################################################
 	<Nome>					<Jarra(Repositório)>"
 rm -Rf /tmp/book2
while IFS= read -r line
do
   echo $line | awk '{print "  "$1"					"$3}' >> /tmp/book2
done < /tmp/book

# if [ "$whoami"=="root" ]; then chmod 777 /tmp/book2; fi
sed -i '/aio:/d' /tmp/book2
cat /tmp/book2
 echo " #######################################################
 #######################################################"
}

MOVEAPP(){
### Parte dessa função só deve ser chamada se o Produto já existir mas aquele usuario ainda não o tem > somente lincar
echo "Produto: $PRODUTO"
if [ -e "$RECEITA_PASTA/out/$PRODUTO" ]; then cp -Rf $RECEITA_PASTA/out/$PRODUTO $APPS;	#Move o app para a pasta de apps
 chmod 777 $APPS/$PRODUTO; echo "Produto encontrado, movendo para a Mesa"; else echo "produto não existe, ou não encontrado"; fi
#MOVXEKLINK

echo "$ADD: $ADD" >> $JAR/system.aio
#if [ "`whoami`" == "root" ]; then sudo chmod 777 $JAR/system.aio; fi
#if [[ -e "$APPS/$ADD.AppImage" && -e '$APPS/$PRODUTO' ]]; then echo "ligação atualizada"; fi
}

#MOVUPDATELINK(){
#	echo "linkando produto"
#	if [ -e '$APPS/$PRODUTO' ]; then ln -s $APPS/$PRODUTO $APPS/$ADD.AppImage; ln -s $APPS/$ADD.AppImage $LOCALBINS; if [ "`whoami`"=="root" ]; then chmod 777 $APPS/$ADD.AppImage; fi else echo "Produto não movido da pasta OUT"; fi
#}
#MOVXEKLINK(){
#	echo "atualizando link"
#	if [ -e '$APPS/$ADD.AppImage' ]; then rm $APPS/$ADD.AppImage; MOVUPDATELINK; else MOVUPDATELINK; fi
#}
#MOVLINKTOBIN(){
#	echo "ingressão do link ao sistema"
#	if [ "`whoami`" == "root" ]; then troca=troca; else echo "Tornando disponível para o sistema. Digite sua senha 🡣"; fi
#	if [ -e "$BINS/$ADD" ]; then
#	 if [ -L "$BINS/$ADD" ]; then troca=troca; else
#	  sudo mv $BINS/$ADD $BINS/$ADD.old; sudo ln -s $APPS/$ADD.AppImage $BINS/$ADD; sudo chmod 777 $BINS/$ADD; fi
#	else
#	 sudo ln -s $APPS/$ADD.AppImage $BINS/$ADD; sudo chmod 777 $BINS/$ADD;
#	fi
#}

MOUNTPAGE(){
	# MainCSS='<link rel="stylesheet" type="text/css" href="'
# Css01=$MainCSS$RAIZ'/andryeltj/aio/master/store/main.css">'
 CssLk01=`curl $RAIZ/andryeltj/aio/master/store/main.css`
 Css01="<style>"$CssLk01"</style>"
 JsMain='<script type="text/javascript" src="'$RAIZ'/andryeltj/aio/master/store/jquery.js"></script>'
 HTMLINFO="<head><title>Store</title><meta chaset=UTF-8><link href='https://fonts.googleapis.com/css2?family=Titillium+Web:ital@1&display=swap' rel='stylesheet'> $Css01 $JsMain </head>"
 CList=`cat /tmp/book`
 CBook=`cat /etc/aio/aio.list`
 HtmlHAreas="<textarea class='list'>"$CList"</textarea><textarea class='book'>"$CBook"</textarea>"
 AppInfo="<div class='appinfo'><div class='appname'>Nome do App</div><i>Informação rápida do Aplicativo</i><div class='passing'>°°°°°°°°</div><a class='applogo'>Icon</a></div>"
 CORPO=$HtmlHAreas$AppInfo"<article></article>"
 aio list
 MainBAR="<div class='mainbar'><a class='aiologo'>AIO</a><span class='searchbar' contenteditable='true'></span><div style='float:right'><a>A</a><a href='aio:store-up' onclick='javascript:window.location.reload(true);'>R</a></div>"
 echo "$HTMLINFO<body><center><h1 style='margin:0'>Voce abriu a Loja, Bem vindo!</h1></center><br><div>$CORPO</div>$MainBAR</body>" > /tmp/store.html
	}

NATIVEFIER(){
	#A função deve ser iniciada antes de DOCOOK para baixar no disco a base que vai para a receita.	
	NATIVEFIERCK=`cat $RECEITA_PASTA/$ADD.yml | grep -w "nativefier:" | awk '{print $2}'`
	if [ "$NATIVEFIERCK" == "yes" ]; then
	  if [[ -e "$BASIS/NativefierBasis.tar.xz" ]]; then
	   troca=troca;	  else
	   BASISLINK=`cat $RECEITA_PASTA/$ADD.yml | grep -w "nativefierlink:" | awk '{print $2}'`
	   wget -q --show-progress --no-check-certificate '$BASISLINK' -O $BASIS/NativefierBasis.tar.xz
	  fi
	fi
}

TESTLOCAL(){
echo "##################### $ISLOCAL ###################"
if [ "$ISLOCAL" == "1" ]; then
  echo "##################### $ISLOCAL ###################"
  echo "📜 Offline"
  MSGU004
  OVEN=`cat $RECEITA_PASTA/$ADD.yml | grep "app:" | awk '{print $2}'`
else
  echo "📜 ONLINE"
  GETNETBOOK
  GETRECEITA
  GETSUGESTS
fi
}

HELP(){
  echo "##################################
#Ooops... Algo aconteceu de errado
##################################
#
#As opções corretas são:
#
# add ou install	instala o app
# del ou remove		remove a instalação de um app
# upd ou update		Atualiza up app específico
#	store			Abre a loja
#	store -r		Recarrega a Loja
#	-i			É o mesmo que 'add'
#	-d			É o mesmo que 'del'
#	-u			É o mesmo que 'upd'
#
#
#"
}

############# MENSAGENS DO SISTEMA
MSGA001(){
	echo " "
	}
MSGAE001(){
	notify-send -i "gtk-dialog-warning" "Não encontrado" "O App não foi encontrado nas fontes"
	}
MSGD001(){
	echo " "
	}
MSGU001(){
	notify-send -i gtk-refresh "Atualizando o app: $1 $2 $3 $4"
	}
MSGU002(){
	notify-send -i gtk-yes -u normal "Atualizar" "Instalação de $1 $2 $3 $4 completa"
	}
MSGU003(){
	notify-send -i gtk-refresh "AIO Atualizado"
	}
MSGU004(){
	notify-send -i gtk-yes "A instalação está sendo realizada com uma receita local"
	}
MSGUE001(){
	notify-send -i gtk-dialog-question -u normal "Como?" "Não consegui encontrar o app para atualizar"
}

INSTALLAIO(){
	sudo mkdir $JAR; sudo chmod -R 777 $JAR; sudo apt install build-essential libcurl4 curl;
	GETINTEGRATE=https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64.deb
	wget -q --show-progress -c $GETINTEGRATE -O AppIL.deb && dpkg -i AppIL.deb 
	if [ -e "$JAR" ]; then mv $CAMINHO/aio $JAR; rm -Rf $BINS/aio; ln -s $JAR/aio $BINS/aio; echo " [🖴 ✔] Jarra criada"; else echo "A pasta em JARRA não foi criada"; fi
}

### Lancadores
if [ -e "$APPS" ]; then troca=troca; else sudo mkdir $APPS; sudo chmod -R 777 $APPS; if [ -e "$APPS" ]; then  echo " [📥✔] Pasta de Apps criada"; fi fi
if [[ -e "$RECEITA_PASTA" ]]; then troca=troca; else mkdir $RECEITA_PASTA; sudo chmod -R 777 $RECEITA_PASTA; if [ -e "$RECEITA_PASTA" ]; then echo " [📜✔] Pasta das receitas criada"; fi	fi #Cria a pasta aonde vão ficar as bases
if [[ -e "$BASIS" ]]; then troca=troca; else mkdir $BASIS; sudo chmod -R 777 $BASIS; if [ -e "$BASIS" ]; then echo " [📜✔] Pasta das bases criada"; fi fi 	#Cria a pasta aonde vão ficar as bases
if [ -e "$JAR" ]; then troca=troca; else INSTALLAIO;	#Cria a pasta aonde vão ficar as definições
 
 if [ -e "$BINS/aio" ]; then ln -s $JAR/aio $BINS/aio; fi 
fi
if [ -e "/usr/share/applications/aio.desktop" ]; then troca=troca; else 
echo "[Desktop Entry]
Type=Application
Name=AIO
Exec=aio %u
Icon=utilities-terminal
Terminal=true
MimeType=x-scheme-handler/aio;
Categories=System;
NoDisplay=true" >> $JAR/aio.desktop
sudo cp -f $JAR/aio.desktop /usr/share/applications
fi
if [ -e "$JAR/jar.aio" ]; then troca=troca; else JARCONTENT; fi
if [ -e "$JAR/aio" ]; then troca=troca; if [ -e "$BINS/aio" ]; then troca=troca; else ln -s $JAR/aio $BINS/aio; fi else mv $CAMINHO/aio $JAR; ln -s $JAR/aio $BINS/aio; fi
if [ -e "$JAR/$COMBURENT" ]; then troca=troca; else GETCOMBURENT; fi
if [ -e "$JAR/system.aio" ]; then troca=troca; else echo "" > $JAR/system.aio; sudo chmod 777 $JAR/system.aio; fi
if [ "`whoami`" == "root" ]; then troca=troca; else
 if [ -e "$LOCAL" ]; then troca=troca; else mkdir $LOCAL; fi
 if [ -e "$LOCALBINS" ]; then troca=troca; else mkdir $LOCALBINS; fi
 if [ -e "$LOCALICONS" ]; then troca=troca; else mkdir $LOCALICONS; fi
 if [ -e "$ELINKS" ]; then troca=troca; else mkdir $ELINKS; fi
fi


#### COMANDOS E INTEGRAÇÔES
if [[ "$1" == "add" || "$1" == "install" || "$1" == "-i" ]]; then
 if [[ "`whoami`" == "root" ]]; then echo "Por favor tente instalar sem ser o Administrador"; else
#  echo "`whoami`"
  CHECKINTEGRATE
  TESTLOCAL
  NATIVEFIER
  DOCOOK
  MOVEAPP
#  EXEINTEGRAR
  if [[ "$3" == "--mb" || "$4" == "--mb" ]]; then echo "A Bases serão mantidas"; else DELOVEN; fi
 fi
 
elif [[ "$1" == "del" || "$1" == "remove" || "$1" == "-d" ]]; then
 CKLOCALNAMES
 DEL
 
 
elif [[ "$1" == "list" || "$1" == "-l" ]]; then
 GETNETBOOK
 LISTJAR
 CHECKAIOVERSION
 
 
elif [[ "$1" == "up" || "$1" == "update" || "$1" == "-u" ]]; then
 GETNETBOOK
 CHECKAIOVERSION
 
 
elif [[ "$1" == "atu" || "$1" == "atualizar" || "$1" == "-a" ]]; then
 CKLOCALNAMES
 CALLLOCAL
 CHECKINTEGRATE
 echo "App para atualizar: $ADD"
 TESTLOCAL
 if [ -e "RECEITA_PASTA/$ADD.yml" ]; then
   echo "Receita encontrada no disco"
   MSGU001
   NATIVEFIER
   DOCOOK
   TSTINTEGRAR
   DEL
   if [[ "$3" == "--mb" || "$4" == "--mb" ]]; then echo "A Bases serão mantidas"; else DELOVEN; fi
   MSGU002
 else
   echo "Receita não encontrada"
   echo "A receita buscada foi: $APP"
   MSGUE001
 fi
 
 
elif [[ "$1" == "--help" || "$2" == "--help" || "$3" == "--help" || "$4" == "--help" || "$1" == "help" || "$2" == "help" || "$3" == "help" || "$4" == "help" ]]; then
 HELP
elif [[ "$1" == "store" ]]; then
 if [[ "$3" == "-r" || "$4" == "-r" ]]; then
  MOUNTPAGE
 else
  MOUNTPAGE
  xdg-open file:///tmp/store.html
 fi
elif [[ "$1" == "aio:store-up" ]]; then
 MOUNTPAGE
else
troca=troca
fi
