#!/bin/bash

## APP - Resultado da tabela de conversão de nomes
## OVEN - consta o nome do arquivo para o sistema dentro o *.yml (app:)
## LIGA - Pacote que acabou de ser criado (aio.list).


#cd /apps/receitas
APP=`cat /apps/receitas/system.aio | grep -w "$1$2$3$4:" | awk '{print $2}'` 
echo "App para atualizar: $APP"
if [ -e "$APP.yml" ]; then
 echo "Receita encontrada"
 notify-send -i gtk-refresh "Atualizando o app: $1 $2 $3 $4"
 pkg2appimage $APP.yml
 ls /apps/receitas/out > /apps/receitas/aio.list
 cp /apps/receitas/out/*.AppImage /apps
 OVEN=`cat $APP.yml | grep "app:" | awk '{print $0}'`
 LIGA=`cat /apps/receitas/aio.list`
 rm -Rf /apps/$LIGA.AppImage
 rm -Rf /apps/receitas/out
 rm -Rf /apps/receitas/$OVEN
 ln -s /apps/$LIGA /apps/$OVEN.AppImage
 notify-send -i gtk-yes -u normal "Atualizar" "Instalação de $1 completa"

else
 echo "Receita não encontrada"
 echo "A receita buscada foi: $APP"
 notify-send -i gtk-dialog-question -u normal "Como?" "Não consegui encontrar o app para atualizar"
 what.aio
fi